<a href="https://colab.research.google.com/github/DaianedeOliveira/analisedados-py/blob/main/AnaliseDadosComercial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import pandas as pd
dados = pd.read_excel("Dados_Comerciais.xlsx")
print(dados)

      ID-Produto           Produto         Categoria     Segmento  Fabricante  \
0    SKU-0000001   LG K10 TV Power         Celulares  Corporativo          LG
1    SKU-0000002  Geladeira Duplex  Eletrodomésticos    Doméstico    Brastemp
2    SKU-0000003    Lavadora 11 Kg  Eletrodomésticos    Doméstico    Brastemp
3    SKU-0000004    Lavadora 11 Kg  Eletrodomésticos    Doméstico    Brastemp
4    SKU-0000005    Lavadora 11 Kg  Eletrodomésticos    Doméstico  Electrolux
..           ...               ...               ...          ...         ...
452  SKU-0000453  Geladeira Duplex  Eletrodomésticos    Doméstico    Brastemp
453  SKU-0000454  Geladeira Duplex  Eletrodomésticos    Doméstico    Brastemp
454  SKU-0000455  Morotola Moto G5         Celulares    Doméstico    Motorola
455  SKU-0000456  Geladeira Duplex  Eletrodomésticos    Doméstico          LG
456  SKU-0000457  Geladeira Duplex  Eletrodomésticos    Doméstico    Brastemp

       Loja          Cidade          Estado          Vendedor  ID-Vendedor  \
0    SP8821       São Paulo       São Paulo      Ana Teixeira         1009
1    SP8821       São Paulo       São Paulo      Josias Silva         1006
2    SP8821       São Paulo       São Paulo      Josias Silva         1006
3    SP8821       São Paulo       São Paulo  Mateus Gonçalves         1003
4    SP8821       São Paulo       São Paulo     Artur Moreira         1004
..      ...             ...             ...               ...          ...
452   R1295  Rio de Janeiro  Rio de Janeiro     André Pereira         1002
453   R1295  Rio de Janeiro  Rio de Janeiro     André Pereira         1002
454   R1295  Rio de Janeiro  Rio de Janeiro      Aline Sutter         1008
455   R1295  Rio de Janeiro  Rio de Janeiro     André Pereira         1002
456   R1295  Rio de Janeiro  Rio de Janeiro     André Pereira         1002

     Comissão (Percentual) Data Venda  ValorVenda  Custo
0                        2 2012-10-04      679.00    345
1                        3 2012-01-01      832.00    712
2                        2 2012-02-02      790.00    390
3                        3 2012-03-03      765.32    200
4                        5 2012-04-04      459.89    234
..                     ...        ...         ...    ...
452                      2 2015-09-23      850.00    120
453                      2 2015-10-24      678.00    120
454                      2 2015-11-25     1230.00    120
455                      2 2015-11-26     1234.00    120
456                      2 2015-11-27     1234.00    120

[457 rows x 14 columns]

In [62]:
dados.isnull().sum()

ID-Produto               0
Produto                  0
Categoria                0
Segmento                 0
Fabricante               0
Loja                     0
Cidade                   0
Estado                   0
Vendedor                 0
ID-Vendedor              0
Comissão (Percentual)    0
Data Venda               0
ValorVenda               0
Custo                    0
dtype: int64

In [63]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID-Produto             457 non-null    object
 1   Produto                457 non-null    object
 2   Categoria              457 non-null    object
 3   Segmento               457 non-null    object
 4   Fabricante             457 non-null    object
 5   Loja                   457 non-null    object
 6   Cidade                 457 non-null    object
 7   Estado                 457 non-null    object
 8   Vendedor               457 non-null    object
 9   ID-Vendedor            457 non-null    int64
 10  Comissão (Percentual)  457 non-null    int64
 11  Data Venda             457 non-null    datetime64[ns]
 12  ValorVenda             457 non-null    float64
 13  Custo                  457 non-null    int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(9)
memory usage: 50.1+ KB

In [64]:
dados.head(25)

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
0,SKU-0000001,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
1,SKU-0000002,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,SKU-0000003,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,SKU-0000004,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
4,SKU-0000005,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234
5,SKU-0000006,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,SKU-0000007,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
7,SKU-0000008,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Fernando Zambrini,1007,2,2012-07-04,1229.00,800
8,SKU-0000009,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-08-04,1300.00,400
9,SKU-0000010,Geladeira Duplex,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2012-09-04,1290.00,600
10,SKU-0000011,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,5,2012-09-04,1287.00,560
11,SKU-0000012,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,A9990,Belo Horizonte,Minas Gerais,Josias Silva,1006,5,2012-11-04,1651.00,790
12,SKU-0000013,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,4,2012-11-04,1100.00,790
13,SKU-0000014,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-12-04,1190.00,790
14,SKU-0000015,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2012-12-04,1190.98,790
15,SKU-0000016,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,A9990,Belo Horizonte,Minas Gerais,Rodrigo Fagundes,1005,4,2013-01-02,877.00,120
16,SKU-0000017,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,5,2013-02-02,982.00,120
17,SKU-0000018,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Fernando Zambrini,1007,6,2013-03-02,872.00,120
18,SKU-0000019,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,5,2013-04-02,799.00,120
19,SKU-0000020,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,André Pereira,1002,4,2013-05-02,899.00,120
20,SKU-0000021,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,3,2013-06-02,799.00,120
21,SKU-0000022,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2013-07-02,987.00,120
22,SKU-0000023,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2013-08-02,699.90,120
23,SKU-0000024,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,4,2013-09-02,789.23,120
24,SKU-0000025,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2,2013-10-02,789.34,120

In [65]:
#Caclcular o custo que é menor que R$200 e o valor da venda menor que R$800
dados[(dados['Custo'] > 200 ) & (dados['ValorVenda'] < 800)]

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
0,SKU-0000001,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2,2012-10-04,679.00,345
2,SKU-0000003,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
4,SKU-0000005,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,5,2012-04-04,459.89,234

In [66]:
# Retorna as cinco maiores vendas
dados.nlargest(5, 'ValorVenda')

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
147,SKU-0000148,Samsung Galaxy 8,Celulares,Corporativo,Samsung,A9990,Belo Horizonte,Minas Gerais,Maria Fernandes,1001,2,2013-07-21,3999.0,120
150,SKU-0000151,Samsung Galaxy 8,Celulares,Corporativo,Samsung,V7654,Vitória,Espírito Santo,Artur Moreira,1004,2,2013-10-24,3999.0,120
154,SKU-0000155,Samsung Galaxy 8,Celulares,Corporativo,Samsung,SP8822,São Paulo,São Paulo,Ana Teixeira,1009,2,2014-10-04,3999.0,120
156,SKU-0000157,Samsung Galaxy 8,Celulares,Corporativo,Samsung,SP8822,São Paulo,São Paulo,Mateus Gonçalves,1003,2,2014-02-02,3999.0,120
157,SKU-0000158,Samsung Galaxy 8,Celulares,Corporativo,Samsung,SP8822,São Paulo,São Paulo,Josias Silva,1006,2,2014-03-03,3999.0,120

In [71]:
celular_media = dados.loc[dados['Categoria'] == 'Celulares', 'ValorVenda'].mean()
print('A média do valor de celulares é: R${:.2f}'.format(celular_media))

A média do valor de celulares é: R$2097.91

In [76]:
dados.query('Fabricante == "Brastemp"')

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Comissão (Percentual),Data Venda,ValorVenda,Custo
1,SKU-0000002,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-01-01,832.00,712
2,SKU-0000003,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2,2012-02-02,790.00,390
3,SKU-0000004,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,3,2012-03-03,765.32,200
5,SKU-0000006,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Rodrigo Fagundes,1005,4,2012-05-04,590.98,90
6,SKU-0000007,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,3,2012-06-04,1000.91,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,SKU-0000448,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-05-18,1234.00,120
450,SKU-0000451,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-07-21,800.00,120
452,SKU-0000453,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-09-23,850.00,120
453,SKU-0000454,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-10-24,678.00,120
456,SKU-0000457,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,R1295,Rio de Janeiro,Rio de Janeiro,André Pereira,1002,2,2015-11-27,1234.00,120

In [79]:
media_Brastemp = dados.loc[dados['Fabricante'] == 'Brastemp', 'ValorVenda'].mean()
print('A média do valor da venda da fabricante Brastemp é: R${:.2f}'.format(media_Brastemp))

A média do valor da venda da fabricante Brastemp é: R$1030.96